Repository aadriii03/-ISO24-ISO2-B04, pull requests merged in 2024-11, with the labels that each got.

#11 Diseño it.2
  CDU10-Descubrir_datos_contenidos_en_las_bases_de_datos_de_la_organizacion.vpp
  CDU4_Identificar quién está implicado en los proyectos de los datos.vpp
  CDU6_Definir los dominios de datos.vpp
Labels: diagramas

#14 Codigo con las clases correspondientes de it2
  proyecto_maven_it1_it2.zip
Labels: Código

#18 Pruebas It.2
  FasePruebasIT2.pdf
Labels: documentation

#21 Analisis it.3
  Fase_de_Analisis_Iteracion3_v.1.1.0.pdf
Labels: documentation

#23 Requisitos it.4
  Requisitos_Iteracion4_v.1.1.0.pdf
Labels: documentation

#25 20 diseño it3
  CDU13_Asignar_tareas_mediante_sistema_online.vpp
  CDU2_Documentar los procesos de negocio.vpp
  CDU3_Identificar y documentar los requisitos de datos.vpp
  CDU5_Clasificar_los_datos_en_categorias.vpp
Labels: diagramas

#27 Implementación iteración 3
  proyecto_maven_it1_it2_it3.zip
Labels: Código

#28 Analisis it.4
  Analisis iteracción1.pdf
  Documento_Analisis_Iteracion_4.pdf
  Documento_Requisitos_Iteracion1.pdf
Labels: documentation

#31 Add files via upload
  FasePruebasIT3.pdf
Labels: documentation

#32 Caso de uso 7
  CDU7-Gestionar_permisos_de_acceso.vpp
Labels: diagramas

#34 Requisitos it.5
  Documento de Requisitos y Casos de Uso.pdf
Labels: documentation

#38 Clases implementadas en el proyecto
  isoproyecto-maven_it1_it2_it3_it4.zip
Labels: Código

#39 Pruebas it4
  FasePruebasIT4.pdf
  isoproyecto-maven_it1_it2_it3_it4.zip
Labels: documentation

#43 Subido diagrama CDU14
  CDU14_Comprobar la calidad del dato.vpp
Labels: diagramas

#45 Requisitos_It.6
  Documento_de_Requisitos_y_Casos_de_Uso_-_Iteracion_6.pdf
Labels: documentation

#47 Análisis_it.6
  Documento de Análisis - Iteración 6.pdf
Labels: documentation

#48 Implementación iteración 5
  isoproyecto-maven_it1_it2_it3_it4_it5.zip
Labels: Código

#52 Subido diseño iteración 6
  CDU9_Disponer de un sistema.vpp
Labels: diagramas

#60 Analisis_It.7
  Analisis(Estatico)_CDU12_It.7.vpp
  Analisis_CDU12_It.7.vpp
Labels: diagramas

#67 Versión 1.0.0
  Alerta.java
  CDU10-Descubrir_datos_contenidos_en_las_bases_de_datos_de_la_organizacion.vpp
  CDU11_Describir datos mediante metadatos.vpp
  CDU13_Asignar_tareas_mediante_sistema_online.vpp
  CDU14_Comprobar la calidad del dato.vpp
  CDU1_ Elaborar un Mapa de Activos de Datos.vpp
  CDU2_Documentar los procesos de negocio.vpp
  CDU3_Identificar y documentar los requisitos de datos.vpp
  CDU4_Identificar quién está implicado en los proyectos de los datos.vpp
  CDU5_Clasificar_los_datos_en_categorias.vpp
  CDU6_Definir los dominios de datos.vpp
  CDU7-Gestionar_permisos_de_acceso.vpp
  CDU8_ Crear Nuevos Metadatos de Negocio, Técnicos y Operativos.vpp
  CDU9_Disponer de un sistema.vpp
  Documentación de requisitos y casos de uso IT.2.pdf
  Documento de Análisis - Iteración 6.pdf
  Documento de Análisis IT.2.pdf
  Documento de Requisitos y Casos de Uso.pdf
  Documento_Analisis_It.5.pdf
  Documento_Analisis_Iteracion_4.pdf
  Documento_de_Requisitos_y_Casos_de_Uso_-_Iteracion_6.pdf
  FasePruebasIT1.pdf
  FasePruebasIT2.pdf
  FasePruebasIT3.pdf
  FasePruebasIT4.pdf
  FasePruebasIT5.pdf
  FasePruebasIT6.pdf
  Fase_de_Analisis_Iteracion3_v.1.1.0.pdf
  Reporte.java
  Requisitos_Iteracion4_v.1.1.0.pdf
  Requisitos_iteración3_v1.1.0.pdf
  SistemaGestionDatos.java
  Solicitud.java
  isoproyecto-maven_it1_it2_it3_it4.zip
  isoproyecto-maven_it1_it2_it3_it4_it5.zip
  proyecto_maven_it1.zip
  proyecto_maven_it1_it2.zip
  proyecto_maven_it1_it2_it3.zip
Labels: needfix

#68 Diagrama de clases iteración 7
  Diagrama_clases_it7.vpp
Labels: diagramas

#70 Clases en java it7
  CambioDato.java
  Dato.java
  EstadoDato.java
  RolUsuario.java
  Usuario.java
Labels: Código

#75 Archivo .vpp correspondiente a la fase de requisitos (it.1 - servidor)
  Servidor-B04-ISOII.vpp
Labels: archivo VPP, Requisitos

#77 Análisis it.1
  Servidor-B04-ISOII.vpp
Labels: archivo VPP, Analisis

#79 DISEÑO ITERACIÓN 1
  Servidor-B04-ISOII.vpp
Labels: archivo VPP, Diseño
